apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homie-prod

resources:
  - ../../base
  - gateway.yaml
  - httproute.yaml
  - certificate.yaml
  - cluster-issuer.yaml

# Pin image tags for prod — updated automatically by CI on each push
images:
  - name: ghcr.io/kiukairor/homie-backend
    newTag: sha-6400a1932d45672980db367386c2f0c4b3bd9ce9  # backend
  - name: ghcr.io/kiukairor/homie-frontend
    newTag: sha-6400a1932d45672980db367386c2f0c4b3bd9ce9  # frontend
