apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homie-prod

resources:
  - ../../base
  - gateway.yaml
  - httproute.yaml
  - certificate.yaml
  - cluster-issuer.yaml

# Pin image tags for prod — update these on each release
images:
  - name: ghcr.io/kiukairor/homie-backend
    newTag: latest
  - name: ghcr.io/kiukairor/homie-frontend
    newTag: latest
