bucket   = "homie-tfstate"
key      = "homie/terraform.tfstate"
region   = "uk-london-1"

endpoints = {
  s3 = "https://lrjcxx7ddd3v.compat.objectstorage.uk-london-1.oraclecloud.com"
}

access_key = "00426b9a4f2cf3aaa7aa0ec10172a6e36bfc28d1"
secret_key = "YXflCAOVDic9R1FCYOog8VzJji5FqVSnoB9925AgtbA="

skip_region_validation      = true
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_requesting_account_id  = true
use_path_style              = true
skip_s3_checksum            = true
