apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: homie-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi   # mistral:7b ~4GB, llama3.2:3b ~2GB, leave room for multiple
  storageClassName: local-path
